name: verify

on:
  push:
    branches-ignore:
      - develop
      - main

jobs:
  verify:

    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout
        uses: actions/checkout@v2
      # Setup Java environment
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      # Run maven verify
      - name: Maven verify
        run: mvn verify --batch-mode
